# Generated by Django 5.1.2 on 2024-11-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
