# Generated by Django 5.1.2 on 2024-11-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_contacts', '0004_alter_contact_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
