# Generated by Django 5.1.2 on 2024-11-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_contacts', '0006_alter_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('PROSPECT', 'Prospect'), ('CUSTOMER', 'Customer')], default='Lead', max_length=8),
        ),
    ]
