# Generated by Django 5.1.2 on 2024-11-04 03:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_contacts', '0007_alter_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
